### ISSUE TITLE
using the GUI Button brings Python-Error

### ISSUE THREAD

**Issue by din6885** [cazitouni/QgisGLViewer#8]
Pressing the Button on the UI brings this Error Message:

`2023-10-17T09:41:07     WARNING    Traceback (most recent call last):
              File "C:\Users/rm/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\QgisGLViewer\Windows.py", line 231, in closeEvent
              self.save_data()
              File "C:\Users/rm/AppData/Roaming/QGIS/QGIS3\profiles\Test/python/plugins\QgisGLViewer\Windows.py", line 263, in save_data
              gap = self.gap_spinbox.value()
             AttributeError: 'MainWindow' object has no attribute 'gap_spinbox'`

Nonetheless it shows the Dialog with the Image.

**Comment by vigiles** [comment]
v1.6.1, error:
```
\QgisGLViewer\Handler.py", line 75, in canvasReleaseEvent
              if self.url != 0 and self.direction is not None:
              ^^^^^^^^
             AttributeError: 'PointTool' object has no attribute 'url'
```
